[package]
name = "usb-async"
version = "0.1.0"
authors = ["Dan Ravensloft <dan.ravensloft@gmail.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"

[dependencies]
futures = "0.1"
mio = "0.6"
tokio = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
udev = "0.2"
